# Generated by Django 3.2.6 on 2022-05-21 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('ss1', 'ss1'), ('ss2', 'ss2'), ('ss3', 'ss3')], max_length=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='Student',
            new_name='Pupil',
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=256)),
                ('lastname', models.CharField(max_length=256)),
                ('subject', models.CharField(choices=[('Sos', 'Social Studies'), ('Maths', 'Mathematics'), ('Eng', 'English'), ('Phy', 'Physics'), ('Chem', 'Chemistry'), ('Bio', 'Biology')], max_length=20)),
                ('class_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.classes')),
            ],
        ),
    ]
