# Generated by Django 3.2.6 on 2022-05-21 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20220521_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.classes'),
            preserve_default=False,
        ),
    ]
